// ══════════════════════════════════════════════════════
//  DomoNow · Data de guiones comerciales
// ══════════════════════════════════════════════════════

const SCRIPTS = {
  'llamada-entrante': {
    channel: '📞 Llamada Entrante', cls: 'ch-llamada',
    obj: 'Recopilar información clave, identificar necesidades y convertir en demostración.',
    enfoque: 'El objetivo NO es vender en ese momento. Entender necesidad → generar confianza → mostrar valor → agendar demo.',
    steps: [
      { n:1, t:'Saludo y presentación', sub:'Generar confianza desde el primer contacto',
        s:['"Hola, buen día. Gracias por comunicarte con DomoNow, te habla [Nombre]. ¿Con quién tengo el gusto?"','"Hola [Nombre], cuéntame, ¿en qué te puedo ayudar?"'],
        tip:'Escuchar activamente sin interrumpir' },
      { n:2, t:'Reconocimiento de consulta', sub:'Entender el motivo y pedir permiso para calificar',
        s:['"Perfecto, con gusto te cuento."','"Para poder orientarte mejor, ¿te hago unas preguntas rápidas sobre tu propiedad y cómo están gestionando hoy?"'],
        tip:'Pedir permiso mejora la disposición del prospecto' },
      { n:3, t:'Calificación del prospecto', sub:'Entender contexto operativo y detectar dolor',
        s:['"¿Qué tipo de propiedad están administrando? (PH, conjunto residencial, comercial, etc.)"','"¿Cuántas unidades tienen aproximadamente?"','"¿Cómo están gestionando la administración? ¿Software o Excel y WhatsApp?"','"¿Qué es lo que más se te está dificultando hoy?"'],
        tip:'Aquí ocurre la venta → escuchar y detectar dolor', note:'Identificar volumen = clave para dimensionar oportunidad' },
      { n:4, t:'Evaluación de urgencia', sub:'Entender en qué etapa está el prospecto',
        s:['"¿Están buscando implementar una solución pronto o están evaluando opciones?"'],
        tip:'Urgente → alta prioridad | Exploratorio → seguimiento' },
      { n:5, t:'Proceso de decisión y presupuesto', sub:'Identificar cómo se toma la decisión',
        s:['"¿Quién más participa en la decisión de implementar una solución como esta?"','"¿Tienen algún rango de presupuesto en mente o aún están evaluando opciones?"'],
        tip:'No presionar, solo entender contexto' },
      { n:6, t:'Presentación de solución', sub:'Conectar necesidades detectadas con DomoNow',
        s:['"Con lo que me cuentas, creo que DomoNow puede ayudarte bastante. Es una plataforma que centraliza toda la operación en un solo lugar."','[Comunicación] "Centralizas anuncios, notificaciones y comunicación en un solo canal."','[Mantenimiento] "Organizas solicitudes, asignaciones y seguimiento en tiempo real."','[Financiero] "Automatizas cobros, control de cartera y reportes."','[Seguridad] "Gestionas accesos, visitantes y trazabilidad en tiempo real."'],
        tip:'Adaptar SOLO a la necesidad detectada. No mencionar todo el portafolio.' },
      { n:7, t:'Transición a Demo', sub:'Convertir interés en acción concreta',
        s:['"¿Te hace sentido lo que te estoy mostrando?"','"La mejor forma de verlo es con una demostración personalizada."','"¿Te queda mejor esta semana o la próxima?"','[Si no está listo] "No hay problema, te puedo enviar información y luego lo revisamos juntos."'],
        tip:'Siempre dejar un siguiente paso concreto' },
      { n:8, t:'Cierre de la llamada', sub:'Confirmar y dejar buena experiencia',
        s:['"Perfecto [Nombre], entonces quedamos para [día/hora]. Te estaré enviando la invitación."','"Muchas gracias por tu tiempo, quedo atento a cualquier inquietud."'],
        tip:'Confirmar correo + asistentes' }
    ],
    cta:'Demo agendada o seguimiento con fecha concreta.',
    crm:'Origen del lead · Tipo de propiedad · Nº unidades · Dolor principal · Urgencia · Decisores',
    signals:['El prospecto describe un problema concreto','Existe urgencia o interés real','Pregunta sobre precio o implementación'],
    buenas:['Mantener tono cercano y profesional','Escuchar más de lo que se habla','Adaptar el discurso al cliente','Cerrar siempre con una acción concreta']
  },
  'llamada-fria': {
    channel: '❄️ Llamada en Frío', cls: 'ch-fria',
    obj: 'Despertar interés, identificar necesidad y abrir la puerta a una conversación más profunda.',
    enfoque: 'El objetivo NO es cerrar la venta. Es convertir el contacto en una demo o llamada de descubrimiento.',
    steps: [
      { n:1, t:'Apertura e introducción', sub:'Romper el hielo y pedir permiso para conversar',
        s:['"Hola [Nombre], habla [Tu nombre] de DomoNow. Sé que estás ocupado, así que seré muy breve."','"Trabajamos con administradores y copropiedades ayudándoles a organizar mejor su operación."','"¿Tienes un minuto y te cuento rápidamente por qué te llamo?"'],
        tip:'Directo y respetuoso. La meta NO es vender, es abrir conversación.' },
      { n:2, t:'Generación de relevancia', sub:'Hacer que el prospecto se identifique con una situación real',
        s:['"Hemos visto que muchas copropiedades hoy enfrentan retos muy parecidos: alta carga operativa, comunicación dispersa, poco control en accesos, dificultad para organizar cartera."','[Residencial] "En conjuntos residenciales, el mayor reto suele ser mantener informados a los residentes sin saturar al administrador."','[Comercial] "En propiedades comerciales, el reto está en responder rápido a múltiples solicitudes y mantener trazabilidad."'],
        tip:'NO explicar el producto. Que el cliente diga: "sí, eso nos pasa"' },
      { n:3, t:'Validación del dolor principal', sub:'Hacer hablar al prospecto y detectar su necesidad dominante',
        s:['"De lo que te menciono, ¿hay algo que hoy te esté generando más carga o dificultad?"','"¿Qué es lo que más te consume tiempo actualmente en la administración?"'],
        tip:'Escuchar · No interrumpir · Detectar dolor · Tomar nota en CRM' },
      { n:4, t:'Presentación de solución alineada', sub:'Responder al dolor detectado con propuesta clara',
        s:['"Con lo que me comentas, creo que DomoNow puede ayudarte bastante en ese punto."','"No solo ofrecemos una plataforma, sino una forma más organizada de gestionar la operación desde un solo lugar."','[Seguridad] "Módulo de accesos: visitantes, ingresos y alertas en tiempo real."','[Finanzas] "Módulo financiero: automatiza cobros, cartera y control financiero."','[Comunicación] "Centraliza toda la comunicación: anuncios, recordatorios, notificaciones."','[Mantenimiento] "Organiza solicitudes, asignaciones y seguimiento en tiempo real."'],
        tip:'Adaptar SOLO al dolor detectado en el paso anterior' },
      { n:5, t:'Credibilidad y prueba social', sub:'Reducir resistencia y aumentar confianza',
        s:['"Copropiedades similares a la tuya han logrado con DomoNow mejoras importantes en tiempos de respuesta, comunicación y control operativo."'],
        note:'A futuro: incluir tipo de conjunto · nº de unidades · resultado logrado' },
      { n:6, t:'Cierre a demo', sub:'Convertir el interés en una acción concreta',
        s:['"Lo mejor en este punto es mostrarte cómo funciona en la práctica."','"Podemos hacer una llamada corta de 20 minutos."','"¿Te parece si lo vemos esta semana?"','"Tengo disponible [día/hora] o [otra opción], ¿cuál te funciona mejor?"'],
        tip:'Ofrecer dos horarios cerrados, no una pregunta abierta' },
      { n:7, t:'Manejo de duda suave', sub:'No perder el contacto si el prospecto no está listo',
        s:['"Perfecto, si quieres te puedo enviar información clara y luego lo revisamos juntos."'],
        tip:'Nunca cerrar sin siguiente paso.' },
      { n:8, t:'Cierre de llamada', sub:'Terminar con buena percepción',
        s:['"Muchas gracias por tu tiempo, [Nombre]."','"Estoy seguro de que podemos ayudarte a optimizar bastante la operación."','"Te envío lo que hablamos y quedo muy atento.  Que tengas un excelente día."'],
        tip:'Tono cálido y seguro. No sonar como libreto rígido.' }
    ],
    cta:'Llamada de descubrimiento o demo programada.',
    crm:'Contacto alcanzado · Disposición inicial · Dolor detectado · Herramienta actual · Nivel de interés',
    signals:['Acepta escuchar por un minuto','Reconoce alguno de los dolores planteados','Comparte el proceso actual'],
    buenas:['Ser breve, claro y respetuoso con el tiempo','Escuchar activamente antes de presentar','Hablar de resultados, no de funcionalidades','Cerrar siempre con siguiente paso concreto']
  },
  whatsapp: {
    channel: '💬 WhatsApp', cls: 'ch-whatsapp',
    obj: 'Responder rápido, calificar sin fricción y llevar a una demo.',
    enfoque: 'Mensajes cortos, directos y fáciles de responder. Escribir como conversación, NO como correo.',
    steps: [
      { n:1, t:'Saludo y apertura', sub:'Generar cercanía inmediata',
        s:['«Hola [Nombre], soy Brayan de DomoNow 👋»','«Gracias por escribirnos. Cuéntame, ¿qué te gustaría mejorar hoy en la administración de tu copropiedad?»'],
        tip:'Mensaje corto, directo y fácil de responder' },
      { n:2, t:'Contexto y permiso', sub:'Pedir autorización para hacer preguntas',
        s:['«Perfecto, con gusto te ayudo 🙌»','«Para darte una recomendación más precisa, ¿te hago unas preguntas rápidas sobre tu propiedad?»'],
        tip:'En WhatsApp pedir permiso mejora la tasa de respuesta' },
      { n:3, t:'Calificación del prospecto', sub:'Entender contexto y detectar dolor',
        s:['«¿Qué tipo de propiedad administras? (PH, conjunto, comercial, etc.)»','«¿Cuántas unidades tienen aproximadamente?»','«¿Hoy están usando algún sistema o lo manejan con Excel, WhatsApp u otras herramientas?»','«¿Qué es lo que más te está generando dificultad hoy?»'],
        tip:'Preguntar de una en una. NO responder automático.' },
      { n:4, t:'Evaluación de urgencia', sub:'Identificar intención real',
        s:['«¿Están buscando implementar algo pronto o están evaluando opciones?»'] },
      { n:5, t:'Proceso de decisión', sub:'Entender contexto de compra',
        s:['«Para tenerlo en cuenta, ¿quién más participa en la decisión?»','«¿Están evaluando presupuesto o aún están explorando opciones?»'],
        tip:'No presionar, solo entender' },
      { n:6, t:'Presentación de solución', sub:'Conectar necesidades con valor de forma concisa',
        s:['«Con lo que me cuentas, creo que DomoNow puede ayudarte bastante.»','«Es una plataforma que organiza toda la operación en un solo lugar.»','[Comunicación] «Centralizas toda la comunicación con residentes en un solo canal.»','[Mantenimiento] «Organizas solicitudes y seguimiento en tiempo real.»','[Financiero] «Automatizas cartera y control financiero.»','[Seguridad] «Controlas accesos y visitantes con trazabilidad.»'],
        tip:'Frases cortas, no párrafos largos. Adaptar al dolor detectado.' },
      { n:7, t:'Transición a demo', sub:'Convertir conversación en acción',
        s:['«¿Te hace sentido lo que te cuento?»','«Podemos hacer una demo corta y te muestro cómo aplicaría en tu caso.»','«¿Te queda mejor esta semana o la próxima?»','[Si no está listo] «Perfecto, si quieres te envío info y luego lo revisamos juntos.»'],
        tip:'Si hay alta intención, mover a llamada directamente.' },
      { n:8, t:'Cierre del chat', sub:'Mantener buena experiencia y seguimiento',
        s:['«Gracias por escribirnos, [Nombre] 🙌»','«Quedo atento a lo que necesites.»','«Te envío la información y seguimos en contacto.»'],
        tip:'Confirmar canal de confirmación para la demo' }
    ],
    cta:'Demo o llamada agendada.',
    crm:'Canal WhatsApp · Tipo de propiedad · Unidades · Dolor principal · Interés · Horario propuesto',
    signals:['Responde con contexto específico','Menciona problema concreto','Elige horario o pide invitación'],
    buenas:['Responder rápido (menos de 5 min ideal)','Un mensaje por idea','Pedir permiso antes de hacer preguntas','Usar emojis con moderación']
  },
  correo: {
    channel: '✉️ Correo Electrónico', cls: 'ch-correo',
    obj: 'Confirmar contacto, generar cercanía y llevar hacia una llamada o demo.',
    enfoque: 'El correo NO busca vender. Busca generar respuesta y obtener información para avanzar.',
    steps: [
      { n:1, t:'Asunto del correo', sub:'Generar apertura con asunto claro',
        s:['"Gracias por tu interés en DomoNow"','[Alt.] "Información sobre DomoNow para tu copropiedad"','[Alt.] "Te ayudamos a optimizar tu administración"'],
        tip:'Probar distintos asuntos para mejorar tasa de apertura' },
      { n:2, t:'Apertura del mensaje', sub:'Crear cercanía desde el primer párrafo',
        s:['"Hola [Nombre],"','"Soy Brayan de DomoNow 👋"','"Gracias por escribirnos. Nos alegra mucho poder ayudarte a explorar cómo mejorar la administración de tu copropiedad."'] },
      { n:3, t:'Preguntas de calificación', sub:'Obtener información clave sin hacer el correo pesado',
        s:['1. ¿Qué tipo de propiedad administras y cuántas unidades tienen?','2. ¿Qué es lo que más te está generando dificultad hoy?','3. ¿Están buscando implementar una solución pronto o están evaluando?','4. ¿Quién más participa en la decisión?'],
        tip:'Máximo 4 preguntas. Ofrecer llamada como alternativa.' },
      { n:4, t:'Transición comercial', sub:'Ofrecer valor y siguiente paso concreto',
        s:['"Con esta información puedo orientarte mucho mejor y mostrarte cómo DomoNow se adapta a tu operación."','"Si prefieres, también podemos verlo directamente en una llamada corta."'],
        tip:'El objetivo final es conversación, no correo.' },
      { n:5, t:'Cierre del correo', sub:'Dejar apertura para respuesta',
        s:['"Quedo atento a tu respuesta 🙌"','"Brayan Ospina"','"Equipo Comercial – DomoNow"'],
        note:'Firma personalizada genera más confianza que firma genérica' }
    ],
    cta:'Respuesta al correo o aceptación de llamada corta.',
    crm:'Fuente · Interés inicial · Tipo de propiedad · Unidades · Retos · Decisores · Urgencia',
    signals:['Responde al correo','Comparte información operativa','Solicita reunión o demo'],
    buenas:['Mensajes cortos y escaneables','Evitar bloques largos de texto','Siempre incluir opción de llamada','El correo es un medio, nunca el cierre']
  },
  calificacion: {
    channel: '🎯 Calificación de Leads', cls: 'ch-caliente',
    obj: 'Validar leads calientes, entender contexto y mover a demo.',
    enfoque: 'Esta es la llamada más importante del funnel. El lead ya mostró interés: calificar rápido → detectar oportunidad → mover a demo.',
    steps: [
      { n:1, t:'Saludo y contexto', sub:'Generar cercanía y justificar la llamada',
        s:['"Hola [Nombre], ¿cómo estás? Te habla [Tu nombre] de DomoNow."','"Te contacto porque vi que recientemente [acción: solicitaste información / visitaste nuestra página], y quería entender tu contexto para ver cómo podemos ayudarte."'],
        tip:'Personalizar siempre el origen del lead' },
      { n:2, t:'Validación de contexto', sub:'Entender el perfil del cliente',
        s:['"Para ubicarme mejor, cuéntame: ¿qué tipo de propiedad estás administrando?"','"¿Cuántas unidades tienen aproximadamente?"'] },
      { n:3, t:'Identificación de necesidades', sub:'Detectar problema principal',
        s:['"Muchos administradores hoy tienen retos en comunicación, mantenimiento, cartera o seguridad..."','"En tu caso, ¿qué es lo que más te está generando dificultad hoy?"','"¿Eso cómo te impacta en el día a día?"'],
        tip:'No avanzar hasta entender bien el dolor' },
      { n:4, t:'Conexión con solución', sub:'Relacionar problema con valor DomoNow',
        s:['"Justamente ahí es donde DomoNow aporta valor, porque te permite centralizar [área relevante] en un solo lugar."','"La idea es que tengas más control y menos carga operativa."'] },
      { n:5, t:'Evaluación de urgencia', sub:'Clasificar el lead',
        s:['"¿Estás buscando implementar una solución pronto o estás evaluando opciones?"'],
        tip:'Activo → avanzar rápido | Exploratorio → nutrir y seguimiento' },
      { n:6, t:'Proceso de decisión', sub:'Entender contexto de compra',
        s:['"¿Quién más participa en la decisión de implementar una solución como esta?"','"¿Están evaluando presupuesto o aún están explorando?"'],
        tip:'No presionar, solo mapear el proceso' },
      { n:7, t:'Cierre a demo', sub:'Convertir el lead en oportunidad real',
        s:['"Con lo que me cuentas, veo una muy buena oportunidad de ayudarte."','"Podemos hacer una demo corta donde te muestro cómo aplicaría en tu caso."','"¿Te parece si agendamos 20 minutos?"','"Tengo disponible [día/hora] o [otra opción], ¿cuál te funciona mejor?"'],
        tip:'Ofrecer dos horarios cerrados.' },
      { n:8, t:'Cierre de llamada', sub:'Confirmar y reforzar relación',
        s:['"Gracias por tu tiempo, [Nombre]."','"Estoy seguro de que podemos ayudarte a optimizar la operación."','"Quedo atento y seguimos en contacto."'] }
    ],
    cta:'Demo agendada.',
    crm:'Origen del lead · Tipo de propiedad · Unidades · Dolor principal · Urgencia · Decisores',
    signals:['Describe dolor repetitivo o costoso','Reconoce necesidad de cambio','Acepta horario de demo'],
    buenas:['Personalizar según origen del lead','Hacer preguntas abiertas','Escuchar más de lo que se habla','Cerrar siempre con demo']
  },
  descubrimiento: {
    channel: '🔍 Descubrimiento · SPIN', cls: 'ch-spin',
    obj: 'Entender a profundidad la operación del cliente e identificar problemas reales.',
    enfoque: 'SPIN Selling + Solution Selling. No gana el que mejor presenta. Gana el que mejor entiende.',
    steps: [
      { n:1, t:'Saludo y contexto', sub:'Generar confianza y establecer propósito',
        s:['"Hola [Nombre], ¿cómo estás? Te habla [Tu nombre] de DomoNow."','"Quiero aprovechar esta llamada para entender cómo están gestionando hoy la copropiedad y ver si realmente podemos ayudarte."','"¿Sigues teniendo unos minutos para que conversemos?"'] },
      { n:2, t:'S – Preguntas de Situación', sub:'Entender la operación actual',
        s:['"¿Qué tipo de propiedad estás administrando?"','"¿Cuántas unidades tienen aproximadamente?"','"¿Tienen zonas comunes que requieran gestión frecuente?"','"¿Hoy cómo están gestionando la administración? ¿Software o Excel y WhatsApp?"'],
        note:'S de SPIN: Preguntas de Situación para establecer contexto base' },
      { n:3, t:'P – Preguntas de Problema', sub:'Detectar puntos críticos',
        s:['"Muchos administradores hoy enfrentan dificultades en comunicación, mantenimiento, cartera o seguridad..."','"En tu caso, ¿qué es lo que más te está generando dificultad hoy?"','"¿Eso cómo impacta tu día a día?"','"¿Es algo frecuente o puntual?"'],
        note:'P de SPIN: Preguntas de Problema para detectar puntos de dolor' },
      { n:4, t:'I – Preguntas de Implicación', sub:'Aumentar percepción de urgencia',
        s:['"Si eso continúa así... ¿cómo crees que impacta la operación a largo plazo?"','"¿Ha afectado la satisfacción de los residentes?"','"¿Ha generado quejas o retrasos?"','"¿Ha incrementado la carga operativa del equipo?"'],
        note:'I de SPIN: Que el cliente conecte el problema con sus consecuencias' },
      { n:5, t:'N – Presentación de Solución', sub:'Conectar problema con valor DomoNow',
        s:['"Con lo que me cuentas, creo que DomoNow puede ayudarte bastante."','[Comunicación] "Centralizas toda la comunicación con residentes en un solo canal."','[Mantenimiento] "Organizas solicitudes, asignaciones y seguimiento en tiempo real."','[Financiero] "Automatizas cartera, cobros y control financiero."','[Seguridad] "Gestionas visitantes, accesos y trazabilidad desde un solo sistema."'],
        note:'N de SPIN: El cliente ya siente el dolor → conectar con la solución' },
      { n:6, t:'Validación y criterios de compra', sub:'Confirmar alineación',
        s:['"Con lo que te estoy mostrando, ¿sientes que esto podría ayudarte en tu operación?"','"¿Qué sería lo más importante para ti al implementar una solución así?"'] },
      { n:7, t:'Cierre a demo', sub:'Convertir en oportunidad real',
        s:['"Lo mejor en este punto es que lo veas funcionando en tu contexto."','"¿Te parece si agendamos 20 minutos?"','"Tengo disponible [día/hora] o [otra opción], ¿cuál te funciona mejor?"'] },
      { n:8, t:'Cierre de la llamada', sub:'Reforzar relación y continuidad',
        s:['"Muchas gracias por tu tiempo, [Nombre]."','"Estoy seguro de que podemos ayudarte a optimizar bastante la operación."','"Quedo atento y seguimos en contacto."'] }
    ],
    cta:'Demo personalizada agendada.',
    crm:'Operación actual · Madurez digital · Dolor principal · Impacto · Criterios de compra · Decisores',
    signals:['Conecta el problema con impacto real','Hace preguntas sobre implementación','Pide ver una demo'],
    buenas:['Escuchar más de lo que se habla','Profundizar antes de proponer','No apresurar el pitch','Conectar siempre con el problema real']
  },
  negociacion: {
    channel: '🤝 Negociación & Cierre', cls: 'ch-spin',
    obj: 'Reforzar el valor, demostrar ROI, reducir riesgos percibidos y cerrar la venta.',
    enfoque: 'No negociar desde el precio. Negociar desde el valor. DomoNow se vende como reducción de carga operativa y control.',
    steps: [
      { n:1, t:'Apertura estratégica (Challenger)', sub:'Establecer el contexto de la decisión',
        s:['"Hola [Nombre], gracias por el espacio y por considerar DomoNow."','"Sabemos que implementar una solución como esta es una decisión importante, por eso quiero mostrarte claramente el valor real que puede generar."'] },
      { n:2, t:'Replanteamiento del problema', sub:'Educar y desafiar la percepción actual',
        s:['"Hoy muchas copropiedades creen que el problema es solo tener un sistema..."','"Pero en realidad el problema suele ser la falta de integración y control en los procesos."','"Mencionaste que [dolor específico]. Ahí es donde normalmente se pierde tiempo, se generan reprocesos y se afecta la experiencia del residente."'],
        note:'Challenger: Educá → Retá la situación actual → Posicioná el valor' },
      { n:3, t:'Propuesta de valor y ROI', sub:'Mostrar el retorno tangible',
        s:['"Lo que hemos visto en copropiedades similares: reducción en tiempos de respuesta, menos reprocesos, mayor control operativo, mejora en satisfacción de residentes."'] },
      { n:4, t:'Oferta comercial – Riesgo cero', sub:'Eliminar fricción de entrada',
        s:['"Además, en este momento estamos facilitando la entrada con:"','"→ 2 meses gratis"','"→ Implementación incluida"','"→ Garantía de 12 meses (sin riesgo)"'],
        note:'🔑 Tu mayor diferencial: riesgo cero. Usarlo siempre como argumento de cierre.' },
      { n:5, t:'Cierre Challenger', sub:'Crear momento de decisión',
        s:['"Con todo esto, la pregunta realmente es:"','"¿Te hace sentido implementar algo así ahora o prefieres seguir operando con los retos actuales?"'],
        tip:'(Pausa estratégica después de la pregunta. No llenar el silencio.)' },
      { n:6, t:'Confirmación SPIN', sub:'Reforzar la decisión desde el problema',
        s:['"Para asegurarme de que estamos alineados... Mencionaste que hoy están teniendo dificultades en [problema]."','"Si esto continúa... ¿cómo crees que impacta la operación, los residentes y el equipo?"','"Con esto en mente... ¿ves viable avanzar con la implementación?"'],
        note:'SPIN en cierre: el cliente se convence a sí mismo al responder las preguntas' },
      { n:7, t:'Urgencia y flexibilidad', sub:'Crear razón para decidir ahora',
        s:['[Urgencia] "Los beneficios actuales de entrada solo están disponibles este mes."','[Flexibilidad] "Podemos empezar por los módulos más urgentes y crecer de forma progresiva."','[Flexibilidad] "La implementación se hace por fases para no afectar la operación."'] },
      { n:8, t:'Cierre final', sub:'Definir acción concreta',
        s:['"¿Avanzamos entonces con el siguiente paso?"','"Puedo preparar la propuesta formal para que la revises / presentes a la junta."'],
        tip:'No vendas miedo, vende claridad. El cliente debe sentir seguridad, no presión.' }
    ],
    cta:'Firma de contrato · Aprobación de junta · Demo final con decisores.',
    crm:'Estado del proceso · Objeciones pendientes · Decisores · Oferta presentada · Fecha comprometida',
    signals:['Hace preguntas sobre implementación o soporte','Pide propuesta formal','Involucra a la junta o comité'],
    buenas:['No entrar en descuento inmediato','Hablar en términos de valor, no de precio','Usar pausas estratégicas','Cerrar siempre con acción concreta']
  }
};

const OBJ_FRIA = [
  { icon:'💻', title:'Ya tenemos un sistema', badge:'Muy común', bc:'badge-blue', resp:'«Perfecto, eso es muy común. Muchas copropiedades con las que trabajamos ya tenían algún sistema. Lo que encontraron es que seguían teniendo procesos dispersos. DomoNow integra todo en un solo lugar: comunicación, mantenimiento, seguridad y financiero.»', preguntas:['«¿Hay algo que te gustaría mejorar de lo que tienen hoy?»','«¿Qué tan centralizada tienes hoy la operación?»'], cierre:'«Si quieres, lo revisamos juntos en una llamada corta y comparas sin compromiso.»' },
  { icon:'💰', title:'No tenemos presupuesto', badge:'Alta frecuencia', bc:'badge-orange', resp:'«Totalmente válido. Muchas veces el costo no está en la herramienta, sino en los reprocesos, el tiempo operativo y la falta de control. DomoNow ayuda a reducir carga operativa, lo que termina generando ahorro en tiempo y recursos. También podemos empezar con lo más esencial y crecer de forma progresiva.»', preguntas:['«¿En qué área sientes que hoy se está perdiendo más tiempo o recursos?»','«Si pudieras reducir esa carga, ¿tendría impacto en tu operación?»'], cierre:'«Si quieres, lo vemos y te muestro cómo se traduce en valor real.»' },
  { icon:'⏰', title:'No tengo tiempo ahora', badge:'Alta frecuencia', bc:'badge-orange', resp:'«Lo entiendo completamente, sé que la operación diaria es muy demandante. Justamente por eso creamos DomoNow, para reducir ese tiempo operativo. Podemos agendar algo muy puntual de 15-20 minutos.»', preguntas:[], cierre:'«¿Te parece si lo dejamos agendado en un horario que te funcione mejor?»' },
  { icon:'🔄', title:'No queremos cambiar procesos', badge:'Resistencia al cambio', bc:'badge-purple', resp:'«Es totalmente válido, cambiar genera incertidumbre. Por eso nuestro enfoque es hacer la transición simple y sin afectar la operación. Muchas comunidades ven mejoras rápidas porque todo se vuelve más organizado.»', preguntas:['«¿Qué parte del proceso actual es más importante para ustedes mantener?»'], cierre:'«Si quieres, te muestro cómo sería ese proceso de implementación sin fricción.»' },
  { icon:'📅', title:'No es el momento', badge:'Evasiva', bc:'badge-blue', resp:'«Claro, entiendo. Solo por contexto, ¿hay algo puntual que haga que no sea el momento?»', preguntas:['«¿Qué tendría que pasar para que sí sea el momento?»'], cierre:'«Si quieres, lo vemos rápido y así lo dejas evaluado para cuando lo necesites.»' },
  { icon:'👥', title:'Debemos validarlo internamente', badge:'Proceso de decisión', bc:'badge-green', resp:'«Perfecto, es totalmente normal. De hecho, acompañamos ese proceso con información clara para la junta o el equipo: presentación personalizada, ROI estimado y demo para equipo.»', preguntas:[], cierre:'«Si quieres, podemos hacer una demo donde participen todos y resolver dudas directamente.»' },
  { icon:'🔗', title:'¿Se integra con nuestros sistemas?', badge:'Técnica', bc:'badge-blue', resp:'«Excelente pregunta. Nuestra plataforma está diseñada para adaptarse y convivir con los sistemas actuales. Durante la implementación acompañamos todo el proceso para que sea fluido.»', preguntas:['«¿Qué herramientas usan actualmente?»','«¿Qué parte es clave mantener?»'], cierre:'«Si quieres, revisamos tu caso puntual y vemos cómo se integraría.»' },
  { icon:'📚', title:'La implementación toma tiempo', badge:'Fricción operativa', bc:'badge-orange', resp:'«Totalmente válido. Por eso en DomoNow nos encargamos de la implementación en un alto porcentaje. La plataforma es fácil de usar y acompañamos todo el proceso: implementación guiada, capacitación incluida y soporte continuo.»', preguntas:[], cierre:'«Si quieres, te muestro cómo sería ese proceso paso a paso.»' }
];

const OBJ_CIERRE = [
  { icon:'💵', title:'Es una inversión alta / presupuesto limitado', badge:'Etapa de cierre', bc:'badge-gold', challenger:'«El mayor costo no está en la herramienta, sino en la operación desorganizada: reprocesos, tiempo perdido y falta de control. Hoy puedes empezar sin riesgo: implementación incluida, meses gratis y garantía.»', spin:'«Hoy, ¿cuánto tiempo o recursos se están destinando a procesos manuales? Si eso se optimiza, ¿qué impacto tendría en tu operación?»', cierre:'«Ahí es donde se empieza a ver el retorno real.»' },
  { icon:'🔍', title:'Estamos evaluando otras opciones', badge:'Comparación', bc:'badge-blue', challenger:'«La diferencia normalmente no está en las funciones, sino en qué tan integrada está la solución. DomoNow conecta toda la operación en un solo lugar.»', spin:'«¿Qué es lo más importante para ustedes al evaluar una solución?»', cierre:'«Si quieres, te muestro esa diferencia en una demo práctica.»' },
  { icon:'🏛️', title:'Debemos validarlo con la junta / comité', badge:'Proceso de decisión', bc:'badge-green', challenger:'«En estos casos, lo que más ayuda es mostrar impacto claro en operación y resultados. Podemos apoyarte con información concreta para que la decisión sea más fácil.»', spin:'«¿Qué es lo más importante que necesitan ver para tomar la decisión?»', cierre:'«Si quieres, hacemos una demo con la junta y resolvemos todo en una sola sesión.»' },
  { icon:'👤', title:'Nos preocupa la adopción de los residentes', badge:'Riesgo operativo', bc:'badge-orange', challenger:'«Cuando la herramienta realmente facilita la vida del residente, la adopción es natural. Funciones como comunicación, mantenimiento y accesos generan uso inmediato.»', spin:'«¿Qué crees que valoran más hoy los residentes?»', cierre:'«La adopción crece cuando el valor es evidente desde el inicio.»' },
  { icon:'📈', title:'¿La solución es flexible a futuro?', badge:'Escalabilidad', bc:'badge-purple', challenger:'«DomoNow es modular, lo que significa que puedes crecer o ajustar según evolucione tu comunidad.»', spin:'«¿Qué cambios proyectas a futuro en tu operación?»', cierre:'«No es una herramienta estática, es una solución que evoluciona contigo.»' },
  { icon:'🔧', title:'Nos preocupa la implementación', badge:'Fricción técnica', bc:'badge-orange', challenger:'«En DomoNow nos encargamos de la implementación en un alto porcentaje. La idea es que no te genere carga adicional.»', spin:'«¿Qué parte de la operación crees que podría verse más afectada?»', cierre:'«La implementación está diseñada para facilitar, no complicar.»' },
  { icon:'🎧', title:'¿Tendremos soporte?', badge:'Confianza', bc:'badge-green', challenger:'«Sí, y es una de nuestras mayores fortalezas. No solo implementamos, acompañamos todo el proceso.»', spin:'«¿Qué tipo de soporte sería clave para ustedes?»', cierre:'«No los dejamos solos en ningún momento del proceso.»' }
];

const TIPS = [
  { t:'🧠 Metodología SPIN', items:['S – Situación: entiende el contexto actual antes de cualquier pitch','P – Problema: detecta los puntos de dolor reales del cliente','I – Implicación: ayuda al cliente a conectar el problema con sus consecuencias','N – Necesidad de valor: el cliente se convence a sí mismo al responder'] },
  { t:'⚔️ Metodología Challenger', items:['Educar: aportar una perspectiva nueva que el cliente no tenía','Retar: desafiar la situación actual con un Insight relevante','Controlar: dirigir la conversación hacia el valor de la solución','No negociar desde el precio, negociar desde el valor'], hl:true },
  { t:'📞 Buenas prácticas en llamadas', items:['Escuchar más de lo que se habla (70/30)','Hacer preguntas abiertas antes de proponer','Adaptar el discurso al rol y al dolor detectado','Cerrar SIEMPRE con una acción concreta'] },
  { t:'💬 Buenas prácticas en WhatsApp', items:['Responder en menos de 5 minutos','Un mensaje por idea (no párrafos largos)','Pedir permiso antes de hacer preguntas','Si hay alta intención, mover a llamada directamente'] },
  { t:'✉️ Buenas prácticas en correo', items:['Máximo 4 preguntas de calificación','Siempre ofrecer alternativa de llamada','Menos texto = más respuesta','El correo es un medio, nunca el cierre'] },
  { t:'🏆 Claves de cierre', items:['El precio no es el problema: es falta de valor percibido','El cierre se construye desde el descubrimiento','La garantía (2 meses + implementación + 12m) es tu arma más fuerte','Usar pausas estratégicas después de preguntas de cierre'], hl:true },
  { t:'🚫 Errores a evitar', items:['Hablar solo de funcionalidades (vender resultado, no software)','Defender el precio sin contexto','Aceptar objeciones sin profundizar','Cerrar una llamada sin definir el siguiente paso'] },
  { t:'💎 Pitch de valor DomoNow', items:['❌ "Tenemos una plataforma con varios módulos..."','✅ "Te ayudamos a tener más control, menos reprocesos y una operación más organizada."','Reducción de carga operativa → resultado tangible','Mayor control y trazabilidad → tranquilidad del administrador'], hl:true }
];
